apiVersion: v1
kind: ConfigMap
metadata:
  name: sencillo-general-config
  namespace: sencillo-scheduler
data:
  config.yaml: |-
    app:
      env: "dev"

    logging:
      stdout: true
      level: "debug"

    scheduler:
      name: sencillo-scheduler
      namespace: sencillo-scheduler
      algorithm: "random"
      informerSyncPeriod: "15s"

    connector:
      mode: "inside"
      masterURL: ""
      kubeConfigPath: ""

    cluster:
      edgeNodes: [ "uq7j5k991-01", "uq7g5w631-01", "uq7p7x251-01" ]
      masterNode: "uq7g5t611-01"
