apiVersion: v1
kind: ConfigMap
metadata:
  name: sencillo-general-config
  namespace: sencillo-scheduler
data:
  config.yaml: |-
    app:
      env: "dev"

    logging:
      stdout: true
      level: "debug"

    scheduler:
      name: sencillo-scheduler
      namespace: sencillo-scheduler
      algorithm: "random"
      informerSyncPeriod: "15s"

    connector:
      mode: "inside"
      masterURL: ""
      kubeConfigPath: ""

    cluster:
      edgeNodes: [ "sencillo-evaluation-m02", "sencillo-evaluation-m03", "sencillo-evaluation-m04" ]
      masterNode: "sencillo-evaluation"
