# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: test-subject-service
  namespace: sencillo-scheduler
spec:
  selector:
    app: test-subject
  type: NodePort
  ports:
  - name: test-subject-service
    protocol: TCP
    port: 80
    nodePort: 30020
    targetPort:   "test-app-port"

