app:
  env: "dev"

logging:
  stdout: true
  level: "debug"

scheduler:
  name: sencillo-scheduler
  namespace: sencillo-scheduler
  algorithm: "random"
  informerSyncPeriod: "15s"

connector:
  mode: "outside"
  masterURL: "192.168.103.2"
  kubeConfigPath: "/Users/sinashariati/.kube/config"

cluster:
  edgeNodes: [ "sencillo-debugging-m02", "sencillo-debugging-m03", "sencillo-debugging-m04" ]
  masterNode: "sencillo-debugging"
