app:
  env: "dev"

logging:
  stdout: true
  level: "debug"

scheduler:
  name: "smallest-fitting-edge-node"
  namespace: "smallest-edge-node-first"
  algorithm: "random"
  informerSyncPeriod: "15s"

connector:
  mode: "outside"
  masterURL: "172.20.2.4"
  kubeConfigPath: "/Users/sinashariati/.kube/config"

cluster:
  edgeNodes: [ "uq7j5k991-01", "uq7g5w631-01", "uq7p7x251-01" ]
  masterNode: "uq7g5t611-01"
